ekf_filter_node:
  ros__parameters:
    frequency: 30.0  # Adjust based on your system

    # Sensors being fused
    two_d_mode: true  # Only use x, y, yaw (no 3D motion)

    # Odometry (Wheel Encoder)
    odom0: /diff_cont/odom
    odom0_config: [true, true, false,  # x, y, z
                   false, false, true, # roll, pitch, yaw
                   true, true, false,  # vx, vy, vz
                   false, false, true] # vroll, vpitch, vyaw

    # IMU Data
    imu0: /imu/data_raw
    imu0_config: [false, false, false,  # x, y, z (Position not used)
                  true, true, true,     # roll, pitch, yaw
                  false, false, false,  # vx, vy, vz
                  true, true, true]     # vroll, vpitch, vyaw
    imu0_differential: true  # Use differential mode
    imu0_remove_gravity: true  # Removes gravity effect from acceleration

    # Frame settings
    publish_tf: true       # Publishes a transform
    world_frame: odom      # The global frame
    odom_frame: odom       # Name for the odom frame
    base_link_frame: base_link  # Or base_footprint, if that’s your main link
